<a href="https://colab.research.google.com/github/RubenQuispe/Machine-Learning-con-Python-001/blob/master/Introducci%C3%B3n_a_Python_Cient%C3%ADfico_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a Python Científico
## Mg. Ruben Quispe

# Porque Numpy
* list no tiene buen manejo para los indices cuando se trabaja con listas de datos de más de dos dimensiones.
* list no posee metodos de algebra lineal, ni de transformaciones de datos.
* En otros lenguajes encontramos estructuras de datos altamente optimizadas para poder hacer operaciones algebraicas sobre arrays.

Por sobre Numpy se erige todo un ecosistema de librerias muy utiles que iremos viendo en el recorrido de este curso.

# Crear Arrays


# 1 importar las librerias

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3]) # con una lista
type(a1)

numpy.ndarray

In [ ]:
a2 = np.arange(10) #np.arange es un metodo similar al range del tipo list
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a3 = np.zeros((2,3)) #crear una lista de 2dimensiones pre-rellenado con Zeros
a4 = np.ones((2,3)) #crear un lista de 2 dimensiones pre.rellenado con unos

In [ ]:
a3, a4

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
from IPython.display import display
display(a3); display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

np.linspace(a,b,n) es una función que permite crear arrays de una dimensión, de largo n, y que contienen puntos entre a y b, distanciados de forma regular. La distancia entre cada punto sera de $(b-a)/(n-1)$

In [ ]:
a5 = np.linspace(0,1,11)
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
#Dtypes
a5.dtype

dtype('float64')

# Dimensión  de un array

In [ ]:
display(a1)

array([1, 2, 3])

In [ ]:
a1.shape

(3,)

In [ ]:
display(a3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a3.shape

(2, 3)

In [ ]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [ ]:
# Son los dos arrays iguales?
np.array_equal(a1D,a2D)

False

In [ ]:
1,a1D.shape[0]

(1, 3)

In [ ]:
# Reshaping
new_dims = (1,a1D.shape[0])
a = a1D.reshape(new_dims)

In [ ]:
np.array_equal(a,a2D)

True

# Acceso a elementos y Slicing

In [ ]:
a = np.array([[1,0,3],[6,10,-1], [4,3,5]])
a

array([[ 1,  0,  3],
       [ 6, 10, -1],
       [ 4,  3,  5]])

In [ ]:
a[0,0]

1

In [ ]:
a[2,1]

3

Para acceder a un elemento de un array de dimensión n, la síntaxis es $array[i1, i2, i3,...iN]$.
En este curso y frecuentemente en ML trabajaremos con arrays de dimensión 1 o dimensión 2, por lo que:
* Para un array de 1D: $a[index]$
* Para un array de 2D: $a[index1, index2]$

In [ ]:
a = np.arange(10)
b = np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a[:5] # toma todo los 5 primeros elementos 


array([0, 1, 2, 3, 4])

In [ ]:
b[0:3,1]

array([0., 1., 0.])

In [ ]:
b[2, 0:3]

array([0., 0., 1.])

In [ ]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Slicing de arrays

                      # 5 primeros elementos del array a
                      # esta notación nos permite obtener la segunda línea del array b
                      # tercera columna del array b
                      # todo el array b.

# Operaciones sobre arrays

In [ ]:

# Aritmetica
a = np.arange(4)

print("a     =", a)
print("a + 5 =", a + 5)
print("a - 5 =", a - 5)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a // 2 =", a // 2)  
print("-a     = ", -a)
print("a ** 2 = ", a ** 2)
print("a % 2  = ", a % 2)

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
-a     =  [ 0 -1 -2 -3]
a ** 2 =  [0 1 4 9]
a % 2  =  [0 1 0 1]


In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# Otras ufuncs interesantes
a = np.arange(4)
b = np.arange(1,5)

display(np.exp(a))         # exponencial
display(np.log(b))         # logaritmo natural
display(np.sqrt(a))        # raiz cuadrada
display(np.greater(a,b))   # superior o igual punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b

array([1, 2, 3, 4])

# Rendimiento
Las ufuncs corren a velocidad de código compilado C.
De poder utilizarse se deberían preferir a el uso de for loops.
Un código Numpy solo con funciones nativas, sin bucles, se le llama código "vectorizado".

In [ ]:
%%timeit
a = np.arange(1000000)
b = np.zeros(1000000)
i = 0
for el in a:
    b[i] = el+el
    i+=1

712 ms ± 25.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:

%%timeit
a = np.arange(1000000)
a+a

7.97 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
a+a

1.04 µs ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Estadística y aleatoridad

In [ ]:
# Estadistica
a = np.arange(10)
display(np.mean(a)) # promedio
display(np.median(a))  # mediana

4.5

4.5

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.percentile(a,40) # percentil

3.6

In [ ]:
np.random.random(10) # aleatoriedad

array([0.17219841, 0.04230417, 0.46880594, 0.68342481, 0.33864537,
       0.24917097, 0.56833672, 0.45784508, 0.40570246, 0.67027453])